# Generated by Django 6.0.4 on 2026-05-09 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'acteur")),
            ],
            options={
                'verbose_name': 'Acteur',
                'verbose_name_plural': 'Acteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='movies.acteur', verbose_name='Acteur')),
            ],
            options={
                'verbose_name': 'Casting',
                'verbose_name_plural': 'Castings',
            },
        ),
        migrations.CreateModel(
            name='Critique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la critique')),
                ('texte', models.TextField(verbose_name='Texte de la critique')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note sur 5')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Critique',
                'verbose_name_plural': 'Critiques',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Texte du commentaire')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('critique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='movies.critique', verbose_name='Critique concernée')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('date_sortie', models.DateField(verbose_name='Date de sortie')),
                ('duree_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée en minutes')),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='affiches/', verbose_name='Affiche du film')),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True, verbose_name='Note moyenne')),
                ('nombre_critiques', models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de critiques')),
                ('acteurs', models.ManyToManyField(related_name='films', through='movies.Casting', to='movies.acteur', verbose_name='Casting principal')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='films', to='movies.genre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['titre'],
            },
        ),
        migrations.AddField(
            model_name='critique',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to='movies.film', verbose_name='Film concerné'),
        ),
        migrations.AddField(
            model_name='casting',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='movies.film', verbose_name='Film'),
        ),
        migrations.AddConstraint(
            model_name='critique',
            constraint=models.UniqueConstraint(fields=('film', 'utilisateur'), name='critique_unique_par_utilisateur_et_film'),
        ),
        migrations.AddConstraint(
            model_name='critique',
            constraint=models.CheckConstraint(condition=models.Q(('note__gte', 1), ('note__lte', 5)), name='critique_note_entre_1_et_5'),
        ),
        migrations.AddConstraint(
            model_name='casting',
            constraint=models.UniqueConstraint(fields=('film', 'acteur'), name='casting_film_acteur_unique'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['titre'], name='movies_film_titre_93f52c_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['date_sortie'], name='movies_film_date_so_6c2604_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['note_moyenne'], name='movies_film_note_mo_f1ca00_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['nombre_critiques'], name='movies_film_nombre__6d5129_idx'),
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.CheckConstraint(condition=models.Q(('duree_minutes__gte', 1)), name='film_duree_positive'),
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('note_moyenne__gte', 0), ('note_moyenne__lte', 5)), ('note_moyenne__isnull', True), _connector='OR'), name='film_note_moyenne_entre_0_et_5'),
        ),
    ]
